name: Build PDF
on:
  push:
    branches:
      - main

jobs:
  build-pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_path: docs
          output_dir: tmp
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: tmp/
